name: Build and Test

on:
  workflow_dispatch:
  pull_request:  
    branches:
      - main

env:
  DOTNET_VERSION: "8.x"
  
jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Banking

    steps:
      - uses: actions/checkout@v4
  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore Banking.sln

      - name: Build
        run: dotnet build Banking.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test Banking.sln --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish Banking.sln --configuration Release --no-restore --no-build